### ISSUE TITLE
Any chance to add buttons from the scanner?

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [Celedhrim/scantopl#1]
Hey there. THX for this project here!

I think this project is what I need to bring my Canon ImageFORMULAR DR-2010C to life. My scanner is completely supported by sane, see here: http://www.sane-project.org/man/sane-canon_dr.5.html
An alternative could be the official linux driver from canon from 2010:
https://www.canon-europe.com/support/products/document-scanners/dr-series/imageformula-dr-2010m.html?type=drivers&driverdetailid=tcm:13-1359803&os=all&language=en

Because it has 3 Buttons, I really want to use them:
![scanner](https://user-images.githubusercontent.com/12913436/132811448-e05e3ec2-a0ba-4d49-882c-e8519ef7bb02.jpg)

**Comment by Celedhrim** [comment]
Hi ! 

This software only send files from a directory to paperless when files match a prefix.
It works better with scanservjs 

There is no interaction with scanner directly , just with files in a directory
