### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by ayakael** [Celedhrim/scantopl#3]
In wanting to package scantopl for Alpine Linux, I've noticed this project does not have a license attached to it. This makes packaging impossible.

Would it be possible to choose a license for this project?

**Comment by Celedhrim** [comment]
Hello ! 

Thanks for you interest for this little piece of software.

https://github.com/Celedhrim/scantopl/commit/f8ebbda296b741e9f5ab1ed6b798667de932ed3e put a license :)
