### ISSUE TITLE
Support for arm/v7?

### ISSUE THREAD

**Issue by sshahs** [Celedhrim/scantopl#4]
I keep receiving an 'exec format error' on my Raspberry Pi 4 when trying to deploy the docker image. Presuming armv7 isnt supported, is there a workaround to allow this to work on the armv7 arch?

**Comment by Celedhrim** [comment]
Hello , yes you can build the go binary !

**Comment by Celedhrim** [comment]
Fix with https://github.com/Celedhrim/scantopl/commit/6a7b07530f15c3b5ab8d86208942ea56527a1e54
